/** @type {import('tailwindcss').Config} */
// Kinetic Dark design system — tokens mirror stitch_gymily_buddy_up_flow/kinetic_dark/DESIGN.md.
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  // App is hard-coded dark. Use 'class' (not the default 'media') so NativeWind
  // doesn't throw on web when Expo toggles the document's dark-mode class.
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0b1326',
        'on-background': '#dae2fd',
        surface: '#1E293B',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-variant': '#2d3449',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#bbcabf',
        outline: '#86948a',
        'outline-variant': '#3c4a42',
        primary: '#4edea3',
        'primary-container': '#10b981',
        'on-primary': '#003824',
        'on-primary-container': '#00422b',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#4edea3',
        'inverse-primary': '#006c49',
        secondary: '#adc6ff',
        'secondary-container': '#0566d9',
        'on-secondary': '#002e6a',
        'on-secondary-container': '#e6ecff',
        tertiary: '#ffb3af',
        'tertiary-container': '#fc7c78',
        'on-tertiary': '#650911',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'text-main': '#F8FAFC',
        'text-muted': '#94A3B8',
        'cult-pink': '#FF3278',
        'cult-red': '#F06055',
        'cult-yellow': '#FFDB17',
      },
      fontFamily: {
        // Body/UI = Inter; editorial hero headlines = Playfair Display.
        sans: ['Inter_400Regular'],
        'sans-medium': ['Inter_500Medium'],
        'sans-semibold': ['Inter_600SemiBold'],
        'sans-bold': ['Inter_700Bold'],
        editorial: ['PlayfairDisplay_700Bold'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.64px' }],
        'display-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.56px' }],
        'headline-md': ['24px', { lineHeight: '32px' }],
        'title-sm': ['18px', { lineHeight: '24px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.6px' }],
        'data-num': ['20px', { lineHeight: '24px', letterSpacing: '-0.2px' }],
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'tap-target': '44px',
      },
    },
  },
  plugins: [],
};
